import { motion } from 'framer-motion';
import { FileText, Clock, Users, Pill, Activity, TrendingUp, AlertTriangle, CheckCircle2, Sparkles, Sun } from 'lucide-react';
import DashboardCard from '@/components/shared/DashboardCard';
import StatusBadge from '@/components/shared/StatusBadge';
import { staggerContainer, staggerItem } from '@/hooks/useAnimations';

const briefingSections = [
  {
    icon: Sun,
    title: 'Good Morning, District Officer',
    content: 'Here is your daily briefing for District X on July 8, 2026. All 6 PHCs are operational today.',
    type: 'greeting',
  },
  {
    icon: Users,
    title: 'Patient Summary',
    content: '445 patients visited PHCs yesterday. General Medicine (185) and Emergency (72) were the busiest departments. 12 patients were admitted.',
    type: 'info',
  },
  {
    icon: Pill,
    title: 'Medicine Alerts',
    content: '3 medicines are critically low: Metformin 500mg (45 units), Insulin Regular (15 vials), and Amlodipine 5mg (out of stock). Restock orders recommended.',
    type: 'warning',
  },
  {
    icon: Activity,
    title: 'AI Outbreak Alert',
    content: 'Dengue risk is HIGH in Block A and B with 45 confirmed cases. Vector control teams have been notified. Fever screening camps recommended.',
    type: 'alert',
  },
  {
    icon: TrendingUp,
    title: 'Performance Highlights',
    content: 'PHC Rampur achieved 92% performance score. Overall district score improved by 3 points to 78/100. Great work by the medical team!',
    type: 'success',
  },
  {
    icon: CheckCircle2,
    title: 'Action Items',
    content: '1. Approve medicine restock for 3 critical items. 2. Schedule vector control in Block A & B. 3. Review PHC Sunpur improvement plan.',
    type: 'action',
  },
];

export default function AIBriefing() {
  return (
    <div className="space-y-5 max-w-3xl mx-auto">
      <motion.div variants={staggerContainer} initial="hidden" animate="visible" className="flex items-center gap-3">
        <motion.div variants={staggerItem} className="w-10 h-10 rounded-xl bg-gradient-to-br from-amber-400 to-orange-500 flex items-center justify-center">
          <FileText className="w-5 h-5 text-white" />
        </motion.div>
        <div>
          <motion.h1 variants={staggerItem} className="text-2xl font-bold">AI Daily Briefing</motion.h1>
          <motion.p variants={staggerItem} className="text-muted-foreground text-sm">Your personalized daily summary • July 8, 2026</motion.p>
        </div>
      </motion.div>

      <motion.div variants={staggerContainer} initial="hidden" animate="visible" className="space-y-3">
        {briefingSections.map((section, i) => (
          <motion.div key={i} variants={staggerItem}>
            <DashboardCard noPadding>
              <div className={`p-5 flex items-start gap-4 ${
                section.type === 'greeting' ? 'bg-gradient-to-r from-[#2563EB]/5 to-[#10B981]/5' :
                section.type === 'alert' ? 'bg-red-50 dark:bg-red-950/20' :
                section.type === 'warning' ? 'bg-amber-50 dark:bg-amber-950/20' :
                section.type === 'success' ? 'bg-[#10B981]/5' :
                ''
              }`}>
                <div className={`w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0 ${
                  section.type === 'greeting' ? 'bg-gradient-to-br from-[#2563EB] to-[#10B981]' :
                  section.type === 'alert' ? 'bg-red-100' :
                  section.type === 'warning' ? 'bg-amber-100' :
                  section.type === 'success' ? 'bg-[#10B981]/10' :
                  section.type === 'action' ? 'bg-[#2563EB]/10' :
                  'bg-muted'
                }`}>
                  <section.icon className={`w-5 h-5 ${
                    section.type === 'greeting' ? 'text-white' :
                    section.type === 'alert' ? 'text-red-600' :
                    section.type === 'warning' ? 'text-amber-600' :
                    section.type === 'success' ? 'text-[#10B981]' :
                    section.type === 'action' ? 'text-[#2563EB]' :
                    'text-muted-foreground'
                  }`} />
                </div>
                <div className="flex-1">
                  <h3 className="font-semibold">{section.title}</h3>
                  <p className="text-sm text-muted-foreground mt-1 leading-relaxed">{section.content}</p>
                </div>
              </div>
            </DashboardCard>
          </motion.div>
        ))}
      </motion.div>

      <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.5 }} className="text-center">
        <p className="text-xs text-muted-foreground flex items-center justify-center gap-1">
          <Sparkles className="w-3 h-3" /> Generated by Q-BharatAI at 6:00 AM • Updated every 6 hours
        </p>
      </motion.div>
    </div>
  );
}
